### ISSUE TITLE
rtcagent w/ stripped opensips binary

### ISSUE THREAD

**Issue by ratetel** [sipcapture/rtcagent#9] opened 2024-03-25 13:37 UTC
hello....
we have opensips installed in an lxc with deb 11. We are trying to get rtcagent running with rtcagent opensips -P9061 -S127.0.0.1

resulting in :
opensips_2024/03/25 13:25:29 RTCAGENT :: version :linux_x86_64:0.0.4-20240305-048b153:[CORE]
opensips_2024/03/25 13:25:29 RTCAGENT :: start to run EBPFProbeOpensips module
opensips_2024/03/25 13:25:29 RTCAGENT :: opensips - nosearch: false
2024/03/25 13:25:29 HEP client will be started
2024/03/25 13:25:29 HEP client started
2024/03/25 13:25:29 RTCAGENT :: pid info :616 -127.0.0.1
opensips_2024/03/25 13:25:29 RTCAGENT ::        Module.Run()
opensips_2024/03/25 13:25:29 EBPFProbeOpensips  BPF bytecode filename: [user/bytecode/opensips_kern.o]
opensips_2024/03/25 13:25:29 EBPFProbeOpensips  Opensips: 1, Version:opensips, binrayPath:/usr/sbin/opensips
opensips_2024/03/25 13:25:30 couldn't start bootstrap manager error:4 errors occurred:
        * error:opening uprobe: symbol udp_send: not found , isRet:false, opts:&{0 0 0 0 0}, {UID:, EbpfFuncName:msg_send_udp}
        * error:opening uprobe: symbol udp_send: not found , isRet:true, opts:&{0 0 0 0 0}, {UID:, EbpfFuncName:msg_ret_send_udp}
        * error:opening uprobe: symbol tcp_send: not found , isRet:false, opts:&{0 0 0 0 0}, {UID:, EbpfFuncName:msg_send_tcp}
        * error:opening uprobe: symbol tcp_send: not found , isRet:true, opts:&{0 0 0 0 0}, {UID:, EbpfFuncName:msg_ret_send_tcp}

, probes activation validation failed

we noticed in the opensips_kern.h that in both spots the udp_send function was called, it was commented out.

any advice on what we might be doing wrong?

**Comment by adubovikov** [comment] 2024-04-20 08:33
is it the binary stripped ?

**Comment by voransoy** [comment] 2024-07-24 13:38
Hi there 
I have the same issue with the rtcagent. I have installed the prebuilt binaries with dpkg. 

```
root@mgw:~# rtcagent opensips --hep-server=192.168.0.10 --hep-port=9060 -m /usr/sbin/opensips --hep-transport=udp
opensips_2024/07/24 16:34:53 RTCAGENT :: version :linux_x86_64:0.0.7-20240327-599486c:[CORE]
opensips_2024/07/24 16:34:53 RTCAGENT :: start to run EBPFProbeOpensips module
opensips_2024/07/24 16:34:53 RTCAGENT :: opensips - nosearch: false
2024/07/24 16:34:53 HEP client will be started
2024/07/24 16:34:53 HEP client started
2024/07/24 16:34:53 RTCAGENT :: pid info :789018 -192.168.0.10
opensips_2024/07/24 16:34:53 RTCAGENT ::	Module.Run()
opensips_2024/07/24 16:34:53 EBPFProbeOpensips	BPF bytecode filename: [user/bytecode/opensips_kern.o]
opensips_2024/07/24 16:34:53 EBPFProbeOpensips	Opensips: 1, Version:opensips, binrayPath:/usr/sbin/opensips
opensips_2024/07/24 16:34:54 couldn't start bootstrap manager error:4 errors occurred:
	* error:opening uprobe: symbol proto_udp_send: not found , isRet:false, opts:&{0 0 0 0 0}, {UID:, EbpfFuncName:msg_send_udp}
	* error:opening uprobe: symbol proto_udp_send: not found , isRet:true, opts:&{0 0 0 0 0}, {UID:, EbpfFuncName:msg_ret_send_udp}
	* error:opening uprobe: symbol proto_tcp_send: not found , isRet:false, opts:&{0 0 0 0 0}, {UID:, EbpfFuncName:msg_send_tcp}
	* error:opening uprobe: symbol proto_tcp_send: not found , isRet:true, opts:&{0 0 0 0 0}, {UID:, EbpfFuncName:msg_ret_send_tcp}

, probes activation validation failed
```

**Comment by lmangani** [comment] 2024-07-24 13:44
@voransoy please specify the version of your kernel as well as the opensips version in use

**Comment by voransoy** [comment] 2024-07-24 13:48
Hi there,

```
root@mgw:~# opensips -V
version: opensips 3.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 40206eeef
main.c compiled on  with gcc 10
```

```
root@mgw:~# uname -r
5.10.0-30-amd64
```

**Comment by lmangani** [comment] 2024-07-24 14:07
@voransoy did you attempt building on your system or is this with the generic distribution? If so, could you please try v0.0.8

**Comment by voransoy** [comment] 2024-07-24 14:16
Hi Loranzo
I haven't attempted to build it from source. I have just downloaded the v0.0.8 debian package and it is the same.

```
root@mgw:~# rtcagent opensips --hep-server=192.168.0.10 --hep-port=9060 -m /usr/sbin/opensips --hep-transport=udp
opensips_2024/07/24 17:13:21 RTCAGENT :: version :linux_x86_64:0.0.8-20240724-006bece:[CORE]
opensips_2024/07/24 17:13:21 RTCAGENT :: start to run EBPFProbeOpensips module
opensips_2024/07/24 17:13:21 RTCAGENT :: opensips - nosearch: false
2024/07/24 17:13:21 HEP client will be started
2024/07/24 17:13:21 HEP client started
2024/07/24 17:13:21 RTCAGENT :: pid info :789803 -192.168.0.10
opensips_2024/07/24 17:13:21 RTCAGENT ::	Module.Run()
opensips_2024/07/24 17:13:21 EBPFProbeOpensips	BPF bytecode filename: [user/bytecode/opensips_kern.o]
opensips_2024/07/24 17:13:21 EBPFProbeOpensips	Opensips: 1, Version:opensips, binrayPath:/usr/sbin/opensips
opensips_2024/07/24 17:13:21 couldn't start bootstrap manager error:4 errors occurred:
	* error:opening uprobe: symbol proto_udp_send: not found , isRet:false, opts:&{0 0 0 0 0 }, {UID:, EbpfFuncName:msg_send_udp}
	* error:opening uprobe: symbol proto_udp_send: not found , isRet:true, opts:&{0 0 0 0 0 }, {UID:, EbpfFuncName:msg_ret_send_udp}
	* error:opening uprobe: symbol proto_tcp_send: not found , isRet:false, opts:&{0 0 0 0 0 }, {UID:, EbpfFuncName:msg_send_tcp}
	* error:opening uprobe: symbol proto_tcp_send: not found , isRet:true, opts:&{0 0 0 0 0 }, {UID:, EbpfFuncName:msg_ret_send_tcp}

, probes activation validation failed
```
I will try to build it from the source.

**Comment by lmangani** [comment] 2024-07-24 14:28
Could you confirm if your opensips binary is stripped?

**Comment by voransoy** [comment] 2024-07-24 14:32
I am using prebuild binaries from the official debian repos. I am not sure but it should be stripped.

**Comment by lmangani** [comment] 2024-07-24 14:39
That's most likely the root cause. If this is true, building rtcagent locally will produce the same results.

**Comment by lmangani** [comment] 2024-07-24 16:20
Closing as we have no workaround for stripped binaries. rtcagent currently requires unstripped binaries to probe functions.

**Closed by lmangani** 2024-07-24 16:20 UTC
